### ISSUE TITLE
Need a fallback resource when create_resource fails

### ISSUE THREAD

**Issue by robrwo** [stevan/webmachine-perl#26]
When create_resource fails, Web::Machine returns a 500 error.

It would be nice to specify a "fall-back resource" that is given the same `resource_args` as well as the error, so that the system can query the error and change the status code or error message appropriate.

The use case for this is as follows:

I'd like to use Web::Machine::Resource-subclass that has attributes based on URL parameters (for instance, when dispatched from Web::Simple).  With a fallback resource, I can check that the error is a type constraint on one of the arguments, and return a 400 error (with a useful message about the invalid parameter).

Otherwise, I use an ugly workaround by subclassing Web::Resource and adding a wrapper around create_resource to do this. Something like:

```perl
use strict;
use warnings;

use parent 'Web::Machine';

use Carp qw/ confess /;
use Class::Method::Modifiers qw/ around /;
use Scalar::Util qw/ blessed /;
use Module::Runtime qw/ use_package_optimistically /;
use Try::Tiny;

sub new {
    my ( $class, %args ) = @_;

    if (exists $args{'fallback'}) {
      use_package_optimistically($args{'fallback'})->isa('Web::Machine::Resource')
        || confess 'The fallback class must inherit from Web::Machine::Resource';
    }

    $class->SUPER::new( %args );
}

sub create_resource {
    my ( $self, $request ) = @_;

    my $resource = try {
        $self->SUPER::create_resource($request);
    }
    catch {

        if ( my $fallback = $self->{'fallback'} ) {

            $fallback->new(
                request       => $request,
                response      => $request->new_response,
                error         => $_,
                resource_args => $self->{'resource_args'},
            );

        }
        else {
            die $_;
        }

    };
}

```
But I think this would be a useful feature to be worth merging into the system.

**Comment by stevan** [comment]
See #28 for details
